---
title: "Bank Marketing"
format: docx
editor: visual
---

# Introduction

```{r}
1 + 1
```

# Lit. Review

# Method

# Data Exploration

```{r, Loading Data, warning=FALSE}
#| echo: false
library(caret)
library(ggplot2)
library(MASS)
library(tidyverse)
library(corrplot)
library(car)

bank = read.csv("C:/Users/crew_/OneDrive/Escritorio/Guille/UTSA Masters/MSDA/DA6813/DA6813/bank-additional.csv", sep = ";")

bank = bank %>% 
  select(-duration) #removing duration from dataset
```


```{r, Summary}
summary(bank)
```

```{r}
sum(is.na(bank)) #No NAs

#| echo: false
diabetes_long = diabetes %>% 
  dplyr::select(-Outcome) %>%  # I am excluding the outcome variable
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Value")

# Creating the histogram in a facet view
ggplot(diabetes_long, aes(x = Value)) +
  geom_histogram(bins = 30, fill = "gray", color = "black") +
  facet_wrap(~ Variable, scales = "free") +
  theme_minimal() +
  labs(title = "Distribution of Variables", x = NULL, y = "Frequency") +
  theme(strip.text = element_text(face = "bold"))
```

