---
title: "CaseStudy2"
format: html
editor: visual
---

## data
```{r}
library(tidyverse)
library(readxl)
getwd() #open R project file to have the same file path
test <- read_xlsx("C:/Users/alexm/Downloads/Pract 2/DA6813/Data/BBBC-Test.xlsx")
train <- read_xlsx("C:/Users/alexm/Downloads/Pract 2/DA6813/Data/BBBC-Train.xlsx")
```
### Exploring
```{r}
head(train)
str(train)

histogram(train$Amount_purchased)
histogram(train$Frequency)
histogram(train$Last_purchase)
histogram(train$First_purchase)
histogram(train$P_Youth)
histogram(train$P_DIY)
```
### logistic model
```{r}
### LETS TRY SAME TECHNIQUE BUT WITH LOGISTIC MODEL
#glm model
glm1 <- glm(Choice ~ . -Observation #-Last_purchase -First_purchase
            , data = train, family = binomial) #Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
summary(glm1)
vif(glm1)



# Predict the probability on TEST - cutoff 0.5
test$PredProb <- predict.glm(glm1, newdata = test, type = 'response')

#create Prediction Indicators for y
test$Pred_Y <- ifelse(test$PredProb >= 0.5, 1, 0)

caret::confusionMatrix(as.factor(test$Choice),as.factor(test$Pred_Y), positive = '1') #this function and 

```

