---
title: "Case 4 Customer Retention"
format: docx
editor: visual
---
# START REPORT BELOW

# Executive Summary

*Brief introduction of problem. Summarizes key findings. Summarizes insights behind key findings.*

# Problem

*Clear description of the problem, from an application and theoretical point of view. Outlines the report.*



# Lit. Review

*Discusses and cites existing works in the theoretical and application realm.* 


# Methods

*Discusses types of variables, sample size, and sampling techniques (if any). Discusses the model(s) and its assumptions and limitations.*



# Data

*Discusses how data was handled, i.e. cleaned and preprocessed. Discusses distributions, correlations, etc.*


# Results

*Presents and discusses the results from model(s). Discusses relationships between covariates and response, if possible, and provides deep insights behind relationships in the context of the application.*


# Conclusions

*Concludes with a summary of the aim and results. Discusses alternative methods that can be used.*